name:                pandoc-filter-indent
version:             0.1.0.0
github:              "mjgajda/pandoc-filter-indent"
license:             BSD3
author:              "Michał J. Gajda"
maintainer:          "mjgajda@migamake.com"
copyright:           "AllRightsReserved"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mjgajda/pandoc-filter-indent#readme>

dependencies:
- base >= 4.7 && < 5
- ghc-syntax-highlighter == 0.0.5.0
- text == 1.2.4.0
- blaze-html == 0.9.1.2
- HaTeX
- pandoc-types
- optics-core
- optics-th

library:
  source-dirs: src

executables:
  filter-indent:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pandoc-filter-indent

tests:
  pandoc-filter-indent-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pandoc-filter-indent
